### ISSUE TITLE
 mx.controls::DateField error

### ISSUE THREAD

**Issue by sangeetjha** [Esri/arcgis-samples-flex#20]
Hi, 
I am new to this forum, so I am not sure if I am missing something. I downloaded the latest swc and got the BasicMap sample project. When I tried to run the BasicMap project, it gave me the following error:

"VerifyError: Error #1014: Class mx.controls::DateField could not be found."

I believe, the DateField and basically mx.controls have been used in some skinning part inside the swc. 
I am using Flex SDK 3.7 where I am creating a pure action script Project. Hence, the mx controls are not recognized. Can you please let me know if the usage of mx architecture is mandatory to use this api?

Thanks,
Sangeet

**Comment by dasa** [comment]
> I am using Flex SDK 3.7 where I am creating a pure action script Project.

Do you mean Flash Builder 4.7 and that you created a new "ActionScript Mobile Project"? If so, this includes none of the Flex SDK so it's unsupported.

You can import the BasicMap project into FlashBuilder and then add references to the mx and sparkskins swcs. See instructions in the [README](https://github.com/Esri/arcgis-samples-flex/blob/develop/mobile/README.md).
