### ISSUE TITLE
CSVLayerSample.mxml is using a deprecated CSV feed

### ISSUE THREAD

**Issue by dasa** [Esri/arcgis-samples-flex#23]
Instead of:
http://earthquake.usgs.gov/earthquakes/catalogs/eqs7day-M2.5.txt

Use:
http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.csv

Reference:
http://earthquake.usgs.gov/earthquakes/feed/v1.0/csv.php

**Comment by MehulChoksey** [comment]
Looks good
