### ISSUE TITLE
Replace old Ocean Basemap

### ISSUE THREAD

**Issue by dasa** [Esri/arcgis-samples-flex#24]
Replace this service:
http://services.arcgisonline.com/arcgis/rest/services/Ocean_Basemap/MapServer

With this service:
http://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer

Reference:
http://blogs.esri.com/esri/arcgis/2014/04/28/36572/

**Comment by MehulChoksey** [comment]
Looks good.
