### ISSUE TITLE
GeoRSSLayerSample.mxml - broken because NWS has changed their website

### ISSUE THREAD

**Issue by bsvensson** [Esri/arcgis-samples-flex#26]
http://www.prh.noaa.gov/ptwc/feeds/ptwc_rss_pacific.xml now displays a message about "The PTWC website have moved to http://ptwc.weather.gov. "

Sample: https://developers.arcgis.com/flex/sample-code/georss-layer.htm

We probably should replace with a static georss file hosted together with the sample.

**Comment by hgonzago** [comment]
Tested and it works as expected.
