### ISSUE TITLE
Updates samples using services that are planned to be retired

### ISSUE THREAD

**Issue by bsvensson** [Esri/arcgis-samples-flex#5]
http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Network/USA/NAServer
http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Network/ESRI_DriveTime_US/GPServer

**Comment by lheberlie** [comment]
Samples affected:
https://github.com/Esri/arcgis-samples-flex/blob/develop/web/src/GP_DriveTimePolygons.mxml
https://github.com/Esri/arcgis-samples-flex/blob/develop/web/src/QueryGPResult.mxml
https://github.com/Esri/arcgis-samples-flex/blob/develop/web/src/SpatialRelationships.mxml
